package com.example.SpringDataJpa.resturantApp.MenuItems;

import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import com.example.SpringDataJpa.resturantApp.MenuItems.Dto.MenuItemRequestDto;
import com.example.SpringDataJpa.resturantApp.MenuItems.Dto.MenuItemResponseDto;

@Mapper(componentModel = "spring")
public interface MenuItemMapper {
    @Mapping(target = "itemId", ignore = true)        // Primary key is generated by DB
    @Mapping(target = "category", ignore = true)  // We handle entity fetch manually in Service
    MenuItem toEntity(MenuItemRequestDto dto);
    @Mapping(target = "categoryId",source = "category.categoryId")
    @Mapping(target = "categoryName",source = "category.categoryName")
    MenuItemResponseDto toResponseDto(MenuItem menuItem);
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "itemId", ignore = true)        // Primary key is generated by DB
    @Mapping(target = "category", ignore = true)  // We handle entity fetch manually in Service
    public void updateEntityFromDto(MenuItemRequestDto requestDto,@MappingTarget MenuItem menuItem);


    
}
